import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/51bVNTqHFlL._AC_UL400_.jpg",
    name: "The Alchemist",
    author: "Paulo Coelho ",
    price: 349,
    originalPrice: 699,
    isBestSeller: true,
    category: "fiction",
    rating: 4.5,
    pages: 172,
    delivery: 3,
    categoryTitle: "Fiction",
  },
  {
    _id: uuid(),
    img: "https://rukminim1.flixcart.com/image/612/612/jpu324w0/book/0/9/0/believe-in-yourself-original-imafbzz2h7yfg5zz.jpeg?q=70",
    name: "Believe In Yourself",
    author: "Joseph",
    price: 250,
    originalPrice: 1200,
    isBestSeller: false,
    category: "self-help",
    rating: 4,
    pages: 80,
    delivery: 3,
    categoryTitle: "Self Help",
  },

  {
    _id: uuid(),
    img: "https://rukminim1.flixcart.com/image/612/612/kokdci80/regionalbooks/t/x/c/zero-to-one-original-imag2zzngtfasecu.jpeg?q=70",
    name: "Zero To One",
    author: "Peter Thiel",
    price: 50,
    originalPrice: 500,
    isBestSeller: false,
    category: "fiction",
    rating: 2,
    pages: 224,
    delivery: 3,
    categoryTitle: "Fiction",
  },
  {
    _id: uuid(),
    img: "https://rukminim1.flixcart.com/image/612/612/kufuikw0/book/x/s/w/atomic-habits-original-imag7kbzg2fu8rjv.jpeg?q=70",
    name: "Atomic Habits",
    author: "James Clear",
    price: 390,
    originalPrice: 790,
    isBestSeller: true,
    category: "self-help",
    rating: 4.8,
    pages: 320,
    delivery: 1,
    categoryTitle: "Self Help",
  },
  {
    _id: uuid(),
    img: "https://rukminim1.flixcart.com/image/612/612/kwxv98w0/book/l/z/y/do-epic-shit-original-imag9gcfcwfvwtep.jpeg?q=70",
    name: "Do Epic Shit",
    author: "Ankur Warikoo",
    price: 219,
    originalPrice: 399,
    category: "self-help",
    rating: 4.6,
    pages: 312,
    delivery: 2,
    categoryTitle: "Self Help",
  },

  {
    _id: uuid(),
    img: "https://rukminim1.flixcart.com/image/612/612/kufuikw0/book/0/6/q/ikigai-original-imag7kc7q5ugy2km.jpeg?q=70",
    name: "IKIGAI",
    author: "Hector Garcia",
    price: 600,
    originalPrice: 1500,
    isBestSeller: false,
    category: "non-fiction",
    rating: 4.6,
    pages: 208,
    delivery: 1,
    categoryTitle: "Non-Fiction",
  },
  {
    _id: uuid(),
    img: "https://rukminim1.flixcart.com/image/612/612/kgwld3k0/book/1/9/4/rich-dad-poor-dad-original-imafxf885pytvycy.jpeg?q=70",
    name: "Rich Dad Poor Dad",
    author: "Robert Kiyoski",
    price: 350,
    originalPrice: 500,
    isBestSeller: false,
    category: "non-fiction",
    rating: 2,
    pages: 336,
    delivery: 3,
    categoryTitle: "Non-Fiction",
  },
  {
    _id: uuid(),
    img: "https://rukminim1.flixcart.com/image/612/612/kirr24w0-0/book/k/k/g/the-monk-who-sold-his-ferrari-original-imafyhgacv9jrgv7.jpeg?q=70",
    name: "Monk Who Sold His Ferrari",
    author: "Robin Sharma",
    price: 119,
    originalPrice: 249,
    isBestSeller: false,
    category: "non-fiction",
    rating: 3,
    pages: 198,
    delivery: 1,
    categoryTitle: "Non-Fiction",
  },
  {
    _id: uuid(),
    img: "https://rukminim1.flixcart.com/image/612/612/ki96c280-0/book/3/p/n/one-indian-girl-original-imafy2zrymfbtygz.jpeg?q=70",
    name: "One Indian Girl",
    author: "Chetan Bhagat",
    price: 799,
    originalPrice: 999,
    isBestSeller: false,
    category: "fiction",
    rating: 3.2,
    pages: 250,
    delivery: 4,
    categoryTitle: "Fiction",
  },
  {
    _id: uuid(),
    img: "https://rukminim1.flixcart.com/image/612/612/kjbr8280-0/book/z/r/9/learning-how-to-fly-original-imafyx6zuhvfhv94.jpeg?q=70",
    name: "Learning How To Fly",
    author: "A.P.J Abdul Kalam",
    price: 163,
    originalPrice: 205,
    isBestSeller: false,
    category: "fiction",
    rating: 2.5,
    pages: 176,
    delivery: 1,
    categoryTitle: "Fiction",
  },
  {
    _id: uuid(),
    img: "https://rukminim1.flixcart.com/image/612/612/kwpam4w0/book/r/a/r/-original-imag9bv6bzstsjgk.jpeg?q=70",
    name: "400 Days",
    author: "Chetan Bhagat",
    price: 699,
    originalPrice: 999,
    isBestSeller: false,
    category: "self-help",
    rating: 4,
    pages: 356,
    delivery: 5,
    categoryTitle: "Self Help",
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/41yu2qXhXXL._SX324_BO1,204,203,200_.jpg",
    name: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    price: 299,
    originalPrice: 499,
    isBestSeller: true,
    category: "non-fiction",
    rating: 4.5,
    pages: 416,
    delivery: 1,
    categoryTitle: "Non-Fiction",
  },
];
